name: Check build and compile

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SFML and ASIO
        run: |
          sudo apt-get update
          sudo apt-get install -y libsfml-dev libasio-dev

      - name: build client
        run: |
          cd client/
          make

      - name: build server
        run: |
          cd server/
          make