name: Check build and compile

on:
  push:
    branches:
      - ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name:
      run: |
        make