name: Check build and compile

on:
  push:
    branches:
      - ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: action/checkout@v3

    - name:
      uses: actions/setup-cpp@v2

    - name:
      run: |
        make

    - name: Check for compilation errors
      run: |
        if [ $? -eq 0 ]; then
          echo "Compilation successful"
        else
          echo "Compilation failed"
          exit 1
        fi

